Aao_Milo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_view, name='home-view'),
    path("profiles/", include('profiles.urls', namespace='profiles')),
    path("posts/", include('posts.urls', namespace='posts')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view')
]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')


    def __str__(self):
        return str(self.content[:20])
    
    def num_likes(self):
        return self.liked.all().count()
    
    # No of comments
    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created', )

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)
    
LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Post
        fields = ('content', 'image')

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', 
                            widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm, CommentModelForm
# Create your views here.

def post_comment_create_and_list_view(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    # Post form, comment form
    p_form = PostModelForm()
    c_form = CommentModelForm()

    # Initials
    post_added = False

    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()

    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
    }

    return render(request, 'posts/main.html', context)

def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value == "Like":
                like.value = "Unlike"
            else:
                like.value = "Like"
        else:
            like.value = "Like"

            post_obj.save()
            like.save()
    
    return redirect('posts:main-post-view')

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock title %}

{% block content %}

    <div class="ui grid">
        <div class="row">
            <div class="eleven wide column">
                POSTS
                {% for obj in qs %}
                    <div class= "ui fluid card">
                        <div class= "content">
                            {{obj.content}}
                        </div>
                        <div class= "content">
                            <form action="{% url 'posts:like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{obj.id}}></input>
                                <button class="ui primary button">
                                    {% if profile not in obj.liked.all %}
                                        <i class="thumbs up icon"></i>&nbsp;Like
                                    {% else %}
                                        <i class="thumbs down icon"></i>&nbsp;Unlike
                                    {% endif %}
                                </button>
                                &nbsp; {{obj.num_likes}}
                            </form>
                        </div>
                        <div>
                            {% if obj.comment_set.all %}
                                {% for comment in obj.comment_set.all %}
                                    <p>{{comment.body}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <form action="" method="POST" class="ui form">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{obj.id}}>
                            {{c_form}}
                            <button type="submit" class="ui primary button" name="submit_c_form">Comment</button>
                        </form>
                    </div>
                {% endfor %}
            </div>
            <div class="five wide column">
                {% if post_added %}
                    <div class="ui green message"> Post added! </div>
                {% endif %}
                <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{p_form}}
                    <button type="submit" class="ui button positive" name="submit_p_form">Post</button>
                </form>
            </div>
        </div>
    </div>

    
{% endblock content %}